CREATE DATABASE IF NOT EXISTS katsenbd;

CREATE TABLE employee (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) DEFAULT NULL,
  salary INT(11) DEFAULT NULL, 
  PRIMARY KEY(id)
);


CREATE TABLE campaña (
  idCampaña INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) DEFAULT NULL,
  fechaCampaña DATETIME DEFAULT NULL,
  estado INT(1) DEFAULT NULL, 
  fechaAlta DATETIME DEFAULT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE paciente (
  idPaciente INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) DEFAULT NULL,
  peso INT DEFAULT NULL,
  sexo VARCHAR(50) DEFAULT NULL,
  especie VARCHAR(50) DEFAULT NULL,
  fechaNacimiento DATE DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  img VARCHAR(150) DEFAULT NULL,
  estado INT(1) DEFAULT NULL, 
  fechaAlta DATETIME DEFAULT NULL,
  PRIMARY KEY(id)
);


CREATE TABLE cliente (
  idCliente INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) DEFAULT NULL,
  peso INT DEFAULT NULL,
  sexo VARCHAR(50) DEFAULT NULL,
  especie VARCHAR(50) DEFAULT NULL,
  fechaNacimiento DATE DEFAULT NULL,
  color VARCHAR(50) DEFAULT NULL,
  img VARCHAR(150) DEFAULT NULL,
  estado INT(1) DEFAULT NULL, 
  fechaAlta DATETIME DEFAULT NULL,
  PRIMARY KEY(id)
);


CREATE TABLE cita (
  idCita INT(11) NOT NULL AUTO_INCREMENT,
  costo VARCHAR(100) DEFAULT NULL,
  anticipo INT DEFAULT NULL,
  idCampaña INT DEFAULT NULL,
  idCliente INT DEFAULT NULL,
  idPaciente INT DEFAULT NULL,
  fechaAlta DATETIME DEFAULT NULL,
  PRIMARY KEY(id)
);



